# Generated by Django 2.2.1 on 2019-05-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_categories',
            field=models.ManyToManyField(blank=True, to='books.BookCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='library_branch',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.LibraryBranch'),
        ),
    ]
