# Generated by Django 2.2.1 on 2019-05-11 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190512_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_categories',
            field=models.ManyToManyField(to='books.BookCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='library_branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.LibraryBranch'),
        ),
    ]
