# Generated by Django 2.2.1 on 2019-05-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190512_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_categories',
            field=models.ManyToManyField(blank=True, to='books.BookCategory'),
        ),
    ]
