# Generated by Django 2.2.1 on 2019-05-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190512_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.LibraryBranch'),
        ),
    ]
