# Generated by Django 2.2.1 on 2019-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190512_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
