# Generated by Django 2.2.1 on 2019-05-13 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20190513_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 21, 48, 19, 87525)),
        ),
    ]
